In [1]:
import torch
import numpy as np

# Initializing Tensor 

## Make directly 

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

##  Make from ndarray

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

## Make from other tensor 

In [7]:
x_ones = torch.ones_like(x_data)
print("Ones Tensoe: \n {} \n".format(x_ones))

x_rand = torch.rand_like(x_data, dtype=torch.float)
print("Random Tensor: \n {} \n".format(x_rand))

Ones Tensoe: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8558, 0.0949],
        [0.7605, 0.1524]]) 



## Make by shape?

In [9]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("Random Tensor: \n {} \n".format(rand_tensor))
print("Ones Tensor: \n {} \n".format(ones_tensor))
print("Zeros Tensor: \n {} \n".format(zeros_tensor))

Random Tensor: 
 tensor([[0.1438, 0.6389, 0.0956],
        [0.0007, 0.1774, 0.2580]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Tensor's attribute 

In [10]:
tensor = torch.rand(3, 4)

print("Shape of tensor: {}".format(tensor.shape))
print("Datatype of Tensor: {}".format(tensor.dtype))
print("Device tensor is stored on: {}".format(tensor.device))

Shape of tensor: torch.Size([3, 4])
Datatype of Tensor: torch.float32
Device tensor is stored on: cpu


# Tensor Operation 

In [11]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [17]:
tensor = torch.ones(4, 4)
print("First row: {}".format(tensor[0]))
print("First column: {}".format(tensor[:, 0]))
print("Last column: {}".format(tensor[...,-1]))

tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [22]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y_3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y_3)

####
#### above and below's operations are all same

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [28]:
agg = tensor.sum()
agg_item = agg.item()
### tensor.item() -> convert to python num

print(agg_item, type(agg_item))

12.0 <class 'float'>


In [29]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


# Bridge? 

In [30]:
t =torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [35]:
t.add_(1)
print(t)
print(n)

tensor([5., 5., 5., 5., 5.])
[5. 5. 5. 5. 5.]
